sources:
  - name: "VPN-Fail"
    url: "https://vpn.fail/free-proxy/v2ray"
  - name: "Hideshots"
    url: "https://hideshots.eu/sub.txt"
  - name: "Pawdroid"
    url: "https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub"
  - name: "FreeFQ"
    url: "https://raw.githubusercontent.com/freefq/free/refs/heads/master/v2"
  - name: "Ermaozi"
    url: "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt"
  - name: "Kwinshadow"
    url: "https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/refs/heads/main/sublinks/mix.txt"
  - name: "Proxydaemi"
    url: "https://raw.githubusercontent.com/Proxydaemitelegram/Proxydaemi44/refs/heads/main/Proxydaemi44"
  - name: "Ssrsub"
    url: "https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray"
  - name: "Roosterkid"
    url: "https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY_RAW.txt"
  - name: "Mahdibland"
    url: "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity"
  - name: "F0rc3Run"
    url: "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/main/Special/Telegram.txt"
  - name: "MhdiTaheri"
    url: "https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector_Py/refs/heads/main/sub/Mix/mix.txt"
  - name: "mehran1404"
    url: "https://raw.githubusercontent.com/mehran1404/Sub_Link/refs/heads/main/V2RAY-Sub.txt"
  - name: "liketolivefree"
    url: "https://raw.githubusercontent.com/liketolivefree/kobabi/refs/heads/main/sub.txt"
  - name: "shadowmere"
    url: "https://shadowmere.xyz/api/b64sub/"
  - name: "AzadNetCH"
    url: "https://raw.githubusercontent.com/AzadNetCH/Clash/refs/heads/main/AzadNet.txt"
  - name: "acymz"
    url: "https://raw.githubusercontent.com/acymz/AutoVPN/refs/heads/main/data/V2.txt"
  - name: "istanbulsydneyhotel"
    url: "https://istanbulsydneyhotel.com/blogs/site/sni.php"
  - name: "MhdiTaheri"
    url: "https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/refs/heads/main/sub/mix"
  - name: "aiboboxx"
    url: "https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2"
  - name: "shabane"
    url: "https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt"
  - name: "Firmfox"
    url: "https://raw.githubusercontent.com/Firmfox/Proxify/refs/heads/main/v2ray_configs/seperated_by_protocol/vless.txt"
  - name: "STR97"
    url: "https://raw.githubusercontent.com/STR97/STRUGOV/refs/heads/main/STR.BYPASS"
  - name: "LalatinaHub"
    url: "https://raw.githubusercontent.com/LalatinaHub/Mineral/refs/heads/master/result/nodes"
  - name: "Epodonios"
    url: "https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt"
  - name: "mheidari98"
    url: "https://raw.githubusercontent.com/mheidari98/.proxy/refs/heads/main/all"


threads: 30
timeout: 5
test_url: "https://api.myip.com"
